export default [
	{
		id: 246655,
		video: false,
		vote_count: 9798,
		vote_average: 6.5,
		title: 'X-Men: Apocalypse',
		release_date: '2016-05-18',
		original_language: 'en',
		original_title: 'X-Men: Apocalypse',
		genre_ids: [28, 12, 14, 878],
		backdrop_path: '/2ex2beZ4ssMeOduLD0ILzXKCiep.jpg',
		adult: false,
		overview:
			"After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.",
		poster_path: '/2mtQwJKVKQrZgTz49Dizb25eOQQ.jpg',
		popularity: 60.312,
	},
	{
		adult: false,
		backdrop_path: '/wvTZZwiCvVaqPL7bGCTSGtsPpV4.jpg',
		genre_ids: [28, 12, 878],
		id: 1771,
		original_language: 'en',
		original_title: 'Captain America: The First Avenger',
		overview:
			"During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
		poster_path: '/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
		release_date: '2011-07-22',
		title: 'Captain America: The First Avenger',
		video: false,
		vote_average: 6.9,
		vote_count: 15502,
		popularity: 41.978,
	},
	{
		id: 299537,
		video: false,
		vote_count: 10053,
		vote_average: 7.0,
		title: 'Captain Marvel',
		release_date: '2019-03-06',
		original_language: 'en',
		original_title: 'Captain Marvel',
		genre_ids: [28, 12, 878],
		backdrop_path: '/nBS1vONGYrsL2C68C2oDQ3eKJR1.jpg',
		adult: false,
		overview:
			'The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.',
		poster_path: '/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg',
		popularity: 133.782,
	},
	{
		id: 9738,
		video: false,
		vote_count: 6911,
		vote_average: 5.7,
		title: 'Fantastic Four',
		release_date: '2005-06-29',
		original_language: 'en',
		original_title: 'Fantastic Four',
		genre_ids: [28, 12, 14, 878],
		backdrop_path: '/ePJ3OOj2lE5k7zIeOL2NBDHZhLk.jpg',
		adult: false,
		overview:
			'During a space voyage, four scientists are altered by cosmic rays: Reed Richards gains the ability to stretch his body; Sue Storm can become invisible; Johnny Storm controls fire; and Ben Grimm is turned into a super-strong … thing. Together, these "Fantastic Four" must now thwart the evil plans of Dr. Doom and save the world from certain destruction.',
		poster_path: '/8HLQLILZLhDQWO6JDpvY6XJLH75.jpg',
		popularity: 35.905,
	},
	{
		id: 49521,
		video: false,
		vote_count: 11355,
		vote_average: 6.5,
		title: 'Man of Steel',
		release_date: '2013-06-12',
		original_language: 'en',
		original_title: 'Man of Steel',
		genre_ids: [28, 12, 14, 878],
		backdrop_path: '/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg',
		adult: false,
		overview:
			'A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.',
		poster_path: '/7rIPjn5TUK04O25ZkMyHrGNPgLx.jpg',
		popularity: 48.574,
	},
	{
		adult: false,
		backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
		genre_ids: [28, 12, 878],
		id: 100402,
		original_language: 'en',
		original_title: 'Captain America: The Winter Soldier',
		overview:
			'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
		poster_path: '/wxwt0pLxFZwKzy7pAu8WixadwqO.jpg',
		release_date: '2014-03-20',
		title: 'Captain America: The Winter Soldier',
		video: false,
		vote_average: 7.7,
		vote_count: 13377,
		popularity: 35.098,
	},
	{
		id: 166424,
		video: false,
		vote_count: 4450,
		vote_average: 4.4,
		title: 'Fantastic Four',
		release_date: '2015-08-05',
		original_language: 'en',
		original_title: 'Fantastic Four',
		genre_ids: [28, 12, 878],
		backdrop_path: '/5gGfR5dyOLyjQj2gjTUytreRHg3.jpg',
		adult: false,
		overview:
			'Four young outsiders teleport to a dangerous universe, which alters their physical form in shocking ways. Their lives irrevocably upended, the team must learn to harness their daunting new abilities and work together to save Earth from a former friend turned enemy.',
		poster_path: '/oeMpEsjmiT9PEJbRM1Fm7TZ1dE0.jpg',
		popularity: 31.817,
	},
	{
		id: 379291,
		video: false,
		vote_count: 574,
		vote_average: 7.2,
		title: 'Justice League vs. Teen Titans',
		release_date: '2016-03-29',
		original_language: 'en',
		original_title: 'Justice League vs. Teen Titans',
		genre_ids: [28, 16],
		backdrop_path: '/AjtPveq4ZdDDvMGHY4Vi4LIM8oe.jpg',
		adult: false,
		overview:
			'Robin is sent by Batman to work with the Teen Titans after his volatile behavior botches up a Justice League mission. The Titans must then step up to face Trigon after he possesses the League and threatens to conquer the world.',
		poster_path: '/3G6RPpafXApTzn56cbVqLBp9uSz.jpg',
		popularity: 37.069,
	},
	{
		id: 557,
		video: false,
		vote_count: 12351,
		vote_average: 7.1,
		title: 'Spider-Man',
		release_date: '2002-05-01',
		original_language: 'en',
		original_title: 'Spider-Man',
		genre_ids: [28, 14],
		backdrop_path: '/no2cllXSRA56LPipQnuPlg3RuTL.jpg',
		adult: false,
		overview:
			'After being bitten by a genetically altered spider, nerdy high school student Peter Parker is endowed with amazing powers to become the Amazing superhero known as Spider-Man.',
		poster_path: '/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg',
		popularity: 49.638,
	},
	{
		adult: false,
		backdrop_path: '/hCVQPB77eXBGh9abVdrWtKpKgkN.jpg',
		genre_ids: [12, 28, 878],
		id: 10138,
		original_language: 'en',
		original_title: 'Iron Man 2',
		overview:
			"With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
		poster_path: '/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
		release_date: '2010-04-28',
		title: 'Iron Man 2',
		video: false,
		vote_average: 6.8,
		vote_count: 14936,
		popularity: 61.31,
	},
	{
		id: 271110,
		video: false,
		vote_count: 16801,
		vote_average: 7.4,
		title: 'Captain America: Civil War',
		release_date: '2016-04-27',
		original_language: 'en',
		original_title: 'Captain America: Civil War',
		genre_ids: [28, 12, 878],
		backdrop_path: '/7FWlcZq3r6525LWOcvO9kNWurN1.jpg',
		adult: false,
		overview:
			'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.',
		poster_path: '/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
		popularity: 88.187,
	},
	{
		id: 10195,
		video: false,
		vote_count: 15375,
		vote_average: 6.8,
		title: 'Thor',
		release_date: '2011-04-21',
		original_language: 'en',
		original_title: 'Thor',
		genre_ids: [28, 12, 14],
		backdrop_path: '/c5tewtijj6aixi8zwwPuYJxifBA.jpg',
		adult: false,
		overview:
			"Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
		poster_path: '/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
		popularity: 62.146,
	},
	{
		adult: false,
		backdrop_path: '/xfBnQ4mgf1jYZsscJGJjr6ce0Ar.jpg',
		genre_ids: [878, 28, 12],
		id: 1724,
		original_language: 'en',
		original_title: 'The Incredible Hulk',
		overview:
			'Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with a new, deadly foe.',
		poster_path: '/vcFeElC8eXI668WSIxcDNkJSBxv.jpg',
		release_date: '2008-06-12',
		title: 'The Incredible Hulk',
		video: false,
		vote_average: 6.2,
		vote_count: 7885,
		popularity: 51.894,
	},
	{
		id: 141052,
		video: false,
		vote_count: 9592,
		vote_average: 6.2,
		title: 'Justice League',
		release_date: '2017-11-15',
		original_language: 'en',
		original_title: 'Justice League',
		genre_ids: [28, 12, 14, 878],
		backdrop_path: '/jorgjEk6a0bed6jdR5wu4S6ZvRm.jpg',
		adult: false,
		overview:
			"Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
		poster_path: '/eifGNCSDuxJeS1loAXil5bIGgvC.jpg',
		popularity: 112.893,
	},
	{
		id: 340102,
		video: false,
		vote_count: 240,
		vote_average: 5.9,
		title: 'The New Mutants',
		release_date: '2020-08-26',
		original_language: 'en',
		original_title: 'The New Mutants',
		genre_ids: [28, 12, 27, 878],
		backdrop_path: '/eCIvqa3QVCx6H09bdeOS8Al2Sqy.jpg',
		adult: false,
		overview:
			'Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.',
		poster_path: '/45FNxAIooJFqjsVaCJts9YJHXS4.jpg',
		popularity: 230.104,
	},
	{
		id: 320288,
		video: false,
		vote_count: 3911,
		vote_average: 6.1,
		title: 'Dark Phoenix',
		release_date: '2019-06-05',
		original_language: 'en',
		original_title: 'Dark Phoenix',
		genre_ids: [28, 12, 878],
		backdrop_path: '/phxiKFDvPeQj4AbkvJLmuZEieDU.jpg',
		adult: false,
		overview:
			"The X-Men face their most formidable and powerful foe when one of their own, Jean Grey, starts to spiral out of control. During a rescue mission in outer space, Jean is nearly killed when she's hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. The X-Men must now band together to save her soul and battle aliens that want to use Grey's new abilities to rule the galaxy.",
		poster_path: '/cCTJPelKGLhALq3r51A9uMonxKj.jpg',
		popularity: 120.299,
	},
	{
		adult: false,
		backdrop_path: '/dJMq14I3XoadBFH0nEkZPmWGvhN.jpg',
		genre_ids: [27, 28],
		id: 36647,
		original_language: 'en',
		original_title: 'Blade',
		overview:
			"When Blade's mother was bitten by a vampire during pregnancy, she did not know that she gave her son a special gift while dying—all the good vampire attributes in combination with the best human skills. Blade and his mentor battle an evil vampire rebel who plans to take over the outdated vampire council, capture Blade and resurrect a voracious blood god.",
		poster_path: '/PDuKQeQkRHkdx7rY147VBVN5Ef.jpg',
		release_date: '1998-08-21',
		title: 'Blade',
		video: false,
		vote_average: 6.7,
		vote_count: 3916,
		popularity: 31.552,
	},
	{
		id: 1726,
		video: false,
		vote_count: 19066,
		vote_average: 7.6,
		title: 'Iron Man',
		release_date: '2008-04-30',
		original_language: 'en',
		original_title: 'Iron Man',
		genre_ids: [28, 12, 878],
		backdrop_path: '/vbY95t58MDArtyUXUIb8Fx1dCry.jpg',
		adult: false,
		overview:
			'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
		poster_path: '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
		popularity: 76.148,
	},
	{
		id: 68721,
		video: false,
		vote_count: 16622,
		vote_average: 6.9,
		title: 'Iron Man 3',
		release_date: '2013-04-18',
		original_language: 'en',
		original_title: 'Iron Man 3',
		genre_ids: [28, 12, 878],
		backdrop_path: '/2ymO6kST1wwtuSlHifAoG2n2fe5.jpg',
		adult: false,
		overview:
			"When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
		poster_path: '/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg',
		popularity: 76.977,
	},
	{
		id: 99861,
		video: false,
		vote_count: 16495,
		vote_average: 7.3,
		title: 'Avengers: Age of Ultron',
		release_date: '2015-04-22',
		original_language: 'en',
		original_title: 'Avengers: Age of Ultron',
		genre_ids: [28, 12, 878],
		backdrop_path: '/8i6ZDk97Vyh0jHohMG4vFeFuKJh.jpg',
		adult: false,
		overview:
			'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
		poster_path: '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
		popularity: 100.331,
	},
];
