export default [
	{
		id: 68721,
		video: false,
		vote_count: 16624,
		vote_average: 6.9,
		title: 'Iron Man 3',
		release_date: '2013-04-18',
		original_language: 'en',
		original_title: 'Iron Man 3',
		genre_ids: [28, 12, 878],
		backdrop_path: '/2ymO6kST1wwtuSlHifAoG2n2fe5.jpg',
		adult: false,
		overview:
			"When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
		poster_path: '/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg',
		popularity: 55.452,
	},
	{
		adult: false,
		backdrop_path: '/hCVQPB77eXBGh9abVdrWtKpKgkN.jpg',
		genre_ids: [12, 28, 878],
		id: 10138,
		original_language: 'en',
		original_title: 'Iron Man 2',
		overview:
			"With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
		poster_path: '/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
		release_date: '2010-04-28',
		title: 'Iron Man 2',
		video: false,
		vote_average: 6.8,
		vote_count: 14939,
		popularity: 56.3,
	},
	{
		id: 10195,
		video: false,
		vote_count: 15379,
		vote_average: 6.8,
		title: 'Thor',
		release_date: '2011-04-21',
		original_language: 'en',
		original_title: 'Thor',
		genre_ids: [28, 12, 14],
		backdrop_path: '/c5tewtijj6aixi8zwwPuYJxifBA.jpg',
		adult: false,
		overview:
			"Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
		poster_path: '/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
		popularity: 57.676,
	},
	{
		adult: false,
		backdrop_path: '/wvTZZwiCvVaqPL7bGCTSGtsPpV4.jpg',
		genre_ids: [28, 12, 878],
		id: 1771,
		original_language: 'en',
		original_title: 'Captain America: The First Avenger',
		overview:
			"During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
		poster_path: '/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
		release_date: '2011-07-22',
		title: 'Captain America: The First Avenger',
		video: false,
		vote_average: 6.9,
		vote_count: 15507,
		popularity: 43.05,
	},
	{
		id: 1726,
		video: false,
		vote_count: 19070,
		vote_average: 7.6,
		title: 'Iron Man',
		release_date: '2008-04-30',
		original_language: 'en',
		original_title: 'Iron Man',
		genre_ids: [28, 12, 878],
		backdrop_path: '/vbY95t58MDArtyUXUIb8Fx1dCry.jpg',
		adult: false,
		overview:
			'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
		poster_path: '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
		popularity: 63.825,
	},
	{
		id: 99861,
		video: false,
		vote_count: 16499,
		vote_average: 7.3,
		title: 'Avengers: Age of Ultron',
		release_date: '2015-04-22',
		original_language: 'en',
		original_title: 'Avengers: Age of Ultron',
		genre_ids: [28, 12, 878],
		backdrop_path: '/8i6ZDk97Vyh0jHohMG4vFeFuKJh.jpg',
		adult: false,
		overview:
			'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
		poster_path: '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
		popularity: 82.808,
	},
	{
		id: 76338,
		video: false,
		vote_count: 12415,
		vote_average: 6.6,
		title: 'Thor: The Dark World',
		release_date: '2013-10-29',
		original_language: 'en',
		original_title: 'Thor: The Dark World',
		genre_ids: [28, 12, 14],
		backdrop_path: '/uhYoytlNaq46dG81wLmHqaSuzWu.jpg',
		adult: false,
		overview:
			'Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.',
		poster_path: '/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg',
		popularity: 53.339,
	},
	{
		adult: false,
		backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
		genre_ids: [28, 12, 878],
		id: 100402,
		original_language: 'en',
		original_title: 'Captain America: The Winter Soldier',
		overview:
			'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
		poster_path: '/wxwt0pLxFZwKzy7pAu8WixadwqO.jpg',
		release_date: '2014-03-20',
		title: 'Captain America: The Winter Soldier',
		video: false,
		vote_average: 7.7,
		vote_count: 13385,
		popularity: 37.482,
	},
	{
		id: 1930,
		video: false,
		vote_count: 12141,
		vote_average: 6.6,
		title: 'The Amazing Spider-Man',
		release_date: '2012-06-23',
		original_language: 'en',
		original_title: 'The Amazing Spider-Man',
		genre_ids: [28, 12, 14],
		backdrop_path: '/HVcza6tJtWFrLriuh3Ano4Vt46.jpg',
		adult: false,
		overview:
			"Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
		poster_path: '/jIfkQNARYyERqRAq1p1c8xgePp4.jpg',
		popularity: 42.864,
	},
	{
		adult: false,
		backdrop_path: '/4Ky8OcB0F7x3PRZQIiFFZyf3eIX.jpg',
		genre_ids: [28, 878, 12],
		id: 49538,
		original_language: 'en',
		original_title: 'X-Men: First Class',
		overview:
			'Before Charles Xavier and Erik Lensherr took the names Professor X and Magneto, they were two young men discovering their powers for the first time. Before they were arch-enemies, they were closest of friends, working together with other mutants (some familiar, some new), to stop the greatest threat the world has ever known.',
		poster_path: '/5QId52kcNtbq6w2OS7smwTPFi2.jpg',
		release_date: '2011-06-01',
		title: 'X-Men: First Class',
		video: false,
		vote_average: 7.3,
		vote_count: 9592,
		popularity: 1.391,
	},
	{
		adult: false,
		backdrop_path: '/xfBnQ4mgf1jYZsscJGJjr6ce0Ar.jpg',
		genre_ids: [878, 28, 12],
		id: 1724,
		original_language: 'en',
		original_title: 'The Incredible Hulk',
		overview:
			'Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with a new, deadly foe.',
		poster_path: '/vcFeElC8eXI668WSIxcDNkJSBxv.jpg',
		release_date: '2008-06-12',
		title: 'The Incredible Hulk',
		video: false,
		vote_average: 6.2,
		vote_count: 7885,
		popularity: 50.537,
	},
	{
		id: 49026,
		video: false,
		vote_count: 16627,
		vote_average: 7.7,
		title: 'The Dark Knight Rises',
		release_date: '2012-07-16',
		original_language: 'en',
		original_title: 'The Dark Knight Rises',
		genre_ids: [28, 80, 18, 53],
		backdrop_path: '/yzsegNpkRCPadnWmshrJzT3ardR.jpg',
		adult: false,
		overview:
			"Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
		poster_path: '/vzvKcPQ4o7TjWeGIn0aGC9FeVNu.jpg',
		popularity: 51.301,
	},
	{
		id: 102899,
		video: false,
		vote_count: 14513,
		vote_average: 7.1,
		title: 'Ant-Man',
		release_date: '2015-07-14',
		original_language: 'en',
		original_title: 'Ant-Man',
		genre_ids: [28, 12, 878],
		backdrop_path: '/a7sAqMKv5tkAdMzFfIhPqIBmQ9g.jpg',
		adult: false,
		overview:
			'Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.',
		poster_path: '/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg',
		popularity: 52.63,
	},
	{
		id: 36657,
		video: false,
		vote_count: 8183,
		vote_average: 7.0,
		title: 'X-Men',
		release_date: '2000-07-13',
		original_language: 'en',
		original_title: 'X-Men',
		genre_ids: [28, 12, 878],
		backdrop_path: '/a6MwSrIKmMjs5b8os7eEgQk05yx.jpg',
		adult: false,
		overview:
			'Two mutants, Rogue and Wolverine, come to a private academy for their kind whose resident superhero team, the X-Men, must oppose a terrorist organization with similar powers.',
		poster_path: '/bRDAc4GogyS9ci3ow7UnInOcriN.jpg',
		popularity: 1.519,
	},
	{
		adult: false,
		backdrop_path: '/6MQmtWk4cFwSDyNvIgoJRBIHUT3.jpg',
		genre_ids: [14, 28, 12],
		id: 559,
		original_language: 'en',
		original_title: 'Spider-Man 3',
		overview:
			'The seemingly invincible Spider-Man goes up against an all-new crop of villains—including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.',
		poster_path: '/2jLxKF73SAPkyhIWrnv67IH7kJ1.jpg',
		release_date: '2007-05-01',
		title: 'Spider-Man 3',
		video: false,
		vote_average: 6.2,
		vote_count: 8962,
		popularity: 40.964,
	},
	{
		id: 49521,
		video: false,
		vote_count: 11356,
		vote_average: 6.5,
		title: 'Man of Steel',
		release_date: '2013-06-12',
		original_language: 'en',
		original_title: 'Man of Steel',
		genre_ids: [28, 12, 14, 878],
		backdrop_path: '/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg',
		adult: false,
		overview:
			'A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.',
		poster_path: '/7rIPjn5TUK04O25ZkMyHrGNPgLx.jpg',
		popularity: 48.141,
	},
	{
		adult: false,
		backdrop_path: '/n2W6mzxEC6JqzvyYeZzysJUiTR9.jpg',
		genre_ids: [12, 28, 878, 53],
		id: 36668,
		original_language: 'en',
		original_title: 'X-Men: The Last Stand',
		overview:
			"When a cure is found to treat mutations, lines are drawn amongst the X-Men—led by Professor Charles Xavier—and the Brotherhood, a band of powerful mutants organised under Xavier's former ally, Magneto.",
		poster_path: '/7RSSkRpwvkNN5iKO8zACtBA0KhQ.jpg',
		release_date: '2006-05-24',
		title: 'X-Men: The Last Stand',
		video: false,
		vote_average: 6.4,
		vote_count: 6999,
		popularity: 1.468,
	},
	{
		adult: false,
		backdrop_path: '/fUoXenTsrdUcgG0sLYbOBouvtTs.jpg',
		genre_ids: [12, 28, 53, 878],
		id: 2080,
		original_language: 'en',
		original_title: 'X-Men Origins: Wolverine',
		overview:
			'After seeking to live a normal life, Logan sets out to avenge the death of his girlfriend by undergoing the mutant Weapon X program and becoming Wolverine.',
		poster_path: '/mQglrQzgZT0Oj9cQYPsLI8dsEqB.jpg',
		release_date: '2009-04-28',
		title: 'X-Men Origins: Wolverine',
		video: false,
		vote_average: 6.2,
		vote_count: 7687,
		popularity: 3.625,
	},
	{
		id: 271110,
		video: false,
		vote_count: 16806,
		vote_average: 7.4,
		title: 'Captain America: Civil War',
		release_date: '2016-04-27',
		original_language: 'en',
		original_title: 'Captain America: Civil War',
		genre_ids: [28, 12, 878],
		backdrop_path: '/7FWlcZq3r6525LWOcvO9kNWurN1.jpg',
		adult: false,
		overview:
			'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.',
		poster_path: '/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
		popularity: 80.138,
	},
	{
		id: 558,
		video: false,
		vote_count: 9987,
		vote_average: 7.1,
		title: 'Spider-Man 2',
		release_date: '2004-06-25',
		original_language: 'en',
		original_title: 'Spider-Man 2',
		genre_ids: [28, 12, 14],
		backdrop_path: '/6al048Lat3eLVQOuKtc9h6Tu94d.jpg',
		adult: false,
		overview:
			"Peter Parker is going through a major identity crisis. Burned out from being Spider-Man, he decides to shelve his superhero alter ego, which leaves the city suffering in the wake of carnage left by the evil Doc Ock. In the meantime, Parker still can't act on his feelings for Mary Jane Watson, a girl he's loved since childhood.",
		poster_path: '/olxpyq9kJAZ2NU1siLshhhXEPR7.jpg',
		popularity: 20.467,
	},
];
